
# playwright.yml

# Purpose: Main workflow for running Playwright tests and deploying HTML reports to GitHub Pages.
# Features:
# Runs tests, generates reports, uploads as artifact.
# Deploys reports to gh-pages branch using peaceiris/actions-gh-pages.
# Generates an index page and adds report URLs to the workflow summary.

name: 🎭 Run Playwright Tests

on:
  push:
    branches: '*'
  # pull_request:
  #   branches: [main]
  workflow_dispatch:
    inputs:
      report_type:
        description: 'Which report to upload'
        required: false
        default: 'monocart'

permissions:
  contents: write
  id-token: write  # Required by actions/deploy-pages@v4
  pages: write      # Required to deploy to GitHub Pages
  actions: read
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  tests:
    name: 🧪 Run Playwright Tests
    runs-on: ubuntu-latest
    timeout-minutes: 10
    env:
      REPORT_TYPE: ${{ github.event.inputs.report_type || 'monocart' }}
    outputs:
      report_dir: ${{ steps.report-dir.outputs.name }}

    steps:
      - name: 📥 Checkout Code
        uses: actions/checkout@v4

      - name: 🚠 Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: lts/*

      - name: ♻️ Cache dependencies
        uses: actions/cache@v4
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: ${{ runner.os }}-node-

      - name: ♻️ Cache Playwright Browsers
        uses: actions/cache@v4
        with:
          path: ~/.cache/ms-playwright
          key: playwright-browsers-${{ runner.os }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            playwright-browsers-${{ runner.os }}-

      - name: 🔧 Install dependencies
        run: npm ci

      - name: 🌐 Install Playwright
        run: npx playwright install --with-deps chromium

      - name: 🧪 Run Playwright Tests
        run: npx playwright test --project=chromium -g "test-1.spec.ts"
        continue-on-error: true

      - name: 📂 List test-reports directory
        run: ls -R test-reports

      - name: 🖥️ 📑 Install and Publish CTRF Test Summary Results
        run: |
          npm install -g github-actions-ctrf
          github-actions-ctrf test-reports/ctrf-report.json
        if: always()
          
      - name: 📊 Add Test Summary HTML Table
        if: always()
        run: node .github/dashboard-scripts/lib/step-summary-table.js

      - name: 📁 Set Report Folder Name
        id: report-dir
        run: |
          REPORT_DIR=$(TZ="America/New_York" date +'%Y-%m-%d_%H-%M-%S')_${{ github.run_id }}
          echo "name=$REPORT_DIR" >> $GITHUB_OUTPUT

      - name: 📤 Package report
        run: |
          mkdir -p package/${{ steps.report-dir.outputs.name }}
          cp -r test-reports/${{ env.REPORT_TYPE }}/* package/${{ steps.report-dir.outputs.name }} || echo "No reports to copy"
        env:
            REPORT_DIR: ${{ steps.report-dir.outputs.name }}
            REPORT_TYPE: ${{ env.REPORT_TYPE }}

      - name: 📦 Upload Report Artifact
        uses: actions/upload-artifact@v4
        if: hashFiles('package/**/*') != ''
        with:
          name: report-folder
          path: package/
          retention-days: 30
          if-no-files-found: warn

      - name: 🔗 Add Dashboard URL
        if: always()
        run: |
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "🔗 The new report will be available here after a few minutes: https://miranda-gv.github.io/playwright-test/" >> $GITHUB_STEP_SUMMARY
